# 2D Separable Convolution

In [7]:
import numpy as np
import cv2 as cv
def conv2d_sep(x,x_p,h1):
    y = np.zeros((x.shape[0],x.shape[1]))
    for j in range(x.shape[0]):
        for i in range(x.shape[1]):
        
            k = x_p[j:h1.shape[0]+j,i:i+1]

            y[j,i] = np.matmul(k.T,h1)
    return(y)

def padd_up(x,n):
    return(np.pad(x, [(n, n), (0, 0)], mode='constant'))

# x = np.array([[10,20,30],
#              [40,50,60],
#              [70,80,90]])
x = cv.imread('blox.jpg', cv.IMREAD_GRAYSCALE)
h = np.array([[1, 2, 1],
              [2, 4, 2],
              [1, 2, 1]])

h1 = np.array([[1,2,1]])
h1 = h1.T
h2 = np.array([[1,2,1]])
h2 = h2.T
# h_f = np.matmul(h1,h2)

n = int((h.shape[0]-1)/2)  # pad length

x_p = padd_up(x,n) # input padded

y_first = conv2d_sep(x,x_p,h1) # matrix multiplication

y_f_pad = y_first.T

y_f_pad = padd_up(y_f_pad,n)

y_final = conv2d_sep(y_first.T,y_f_pad,h2)

y_final = y_final.T
print(y_final)



[[2160. 2880. 2880. ... 2889. 2883. 2160.]
 [2880. 3840. 3840. ... 3852. 3844. 2880.]
 [2880. 3840. 3840. ... 3852. 3844. 2880.]
 ...
 [2458. 3295. 3293. ... 3253. 3327. 2521.]
 [2465. 3304. 3333. ... 3345. 3397. 2559.]
 [1851. 2469. 2474. ... 2547. 2573. 1929.]]
