# 2D convolution using Toplitz Matrix

In [2]:
import numpy as np
import cv2 as cv

def pad_shift(h_s,n1):
    
    for i in range(n1-1):
      
        h_g = np.pad(h_s,((i+1,0),(0,0)), 'constant')
        h_s = np.hstack((h_s,h_g[0:h_s.shape[0],0:1]))
    return h_s

# stack the array rows in reverse order(instead of 0,1,2 to 2,1,0) 
def reverse_row_order(g,h,h_res):
    for i in reversed(range(h_res-1)):
    
        z = h[i,:]
        g = np.vstack((g,z))
    return g

#m = np.array([[1, 4, 1, 4], [2, 5, 3, 6], [1, 1, 3, 4], [2, 6, 3, 8]])
m=cv.imread('blox.jpg',cv.IMREAD_GRAYSCALE)
#m = np.array([[1,4,1],
       #         [2,5,3]])

h = np.array([[1, 2, 1],
             [2, 4, 2],
             [1, 2, 1]])
m1 = m.shape[0]
m2 = h.shape[0]
n1 = m.shape[1]
n2 = h.shape[1]

h_res = m1+m2-1
w_res = n1+n2-1

#g = np.zeros((h_res,w_res))

h = np.pad(h,((h_res-m2,0),(0,w_res-n2)), 'constant',constant_values=0)

g = h[h_res-1,:]
g = reverse_row_order(g,h,h_res)
   
#h_f = np.reshape(g,(12,1))
g = g.T

k_i = np.reshape(g[:,0],(w_res,1))

h_1 = pad_shift(k_i,n1)

for i in range (w_res-1):
    #print(i)
    k = np.reshape(g[:,i+1],(w_res,1))
    h_t = pad_shift(k,n1)
    
    
    h_1 = np.vstack((h_1,h_t))

zer_m = np.zeros((w_res,n1))

for j in range(m1-1):
    
    h_n = h_1[0:h_res*w_res-w_res,j*n1:j*n1+n1]
    
    h_f = np.vstack((zer_m,h_n))
    
    h_1 = np.concatenate((h_1,h_f),axis=1)
    
I = np.flipud(m)
I = np.reshape(I,(m1*n1,1))

result_vector = np.matmul(h_1, I)

result_vector = np.reshape(result_vector,(h_res,w_res))
r_v = result_vector[h_res-1:h_res,:]

r_v = reverse_row_order(r_v,result_vector,h_res)

#print("Toplitz Matrix: ")
#print(h_1)
print("resultant Vector: ")
print(r_v)

resultant Vector: 
[[ 240.  720.  960. ...  961.  720.  240.]
 [ 720. 2160. 2880. ... 2883. 2160.  720.]
 [ 960. 2880. 3840. ... 3844. 2880.  960.]
 ...
 [ 820. 2465. 3304. ... 3397. 2559.  852.]
 [ 617. 1851. 2469. ... 2573. 1929.  642.]
 [ 205.  615.  820. ...  859.  643.  214.]]
